"""Init

Revision ID: 8926048dc82f
Revises: 
Create Date: 2026-01-21 16:32:55.357994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8926048dc82f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miasta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.Unicode(length=100), nullable=False),
    sa.Column('ludnosc', sa.Integer(), nullable=True),
    sa.Column('czy_lotnisko', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miasta')
    # ### end Alembic commands ###
